export class Constants {

static HAS_SIGNED_IN = 'HAS_SIGNED_IN';

static SIGN_UP = 'SIGN_UP';
static SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
static SIGN_UP_FAILED = 'SIGN_UP_FAILED';

static SIGN_IN = 'SIGN_IN';
static SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
static SIGN_IN_FAILED = 'SIGN_IN_FAILED'

static LOG_OUT = 'LOG_OUT';
static LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

static REGISTER_DONOR = 'REGISTER_DONOR';
static REGISTER_DONOR_SUCCESS = 'REGISTER_DONOR_SUCCESS';
static REGISTER_DONOR_FAILED = 'REGISTER_DONOR_FAILED';

static VIEW_DONOR = 'VIEW_DONOR'
static VIEW_DONOR_SUCCESS = 'VIEW_DONOR_SUCCESS'
static VIEW_DONOR_FAILED = 'VIEW_DONOR_FAILED'

}